# Generated by Django 2.1.2 on 2018-10-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('event', '0003_auto_20181003_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, to='accounting.Payment'),
        ),
    ]
